# Устанавливаем базовый образ Go
FROM golang:1.23.0-alpine AS builder

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем go.mod и go.sum файлы и устанавливаем зависимости
COPY go.mod go.sum ./
RUN go mod download && echo "Dependencies downloaded successfully" || (echo "Failed to download dependencies" && exit 1)

# Копируем исходный код в контейнер
COPY . .

# Строим приложение
RUN go build -o main ./cmd/api

# Устанавливаем образ для финального контейнера
FROM alpine:latest  

# Устанавливаем необходимые пакеты
RUN apk --no-cache add ca-certificates

# Копируем скомпилированное приложение из предыдущего контейнера
COPY --from=builder /app/main /usr/local/bin/main

# Открываем порт, на котором будет работать приложение
EXPOSE 8080

# Запускаем приложение
CMD ["main"]
