// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddCommentInput struct {
	PostID   string  `json:"postID"`
	ParentID *string `json:"parentID,omitempty"`
	Content  string  `json:"content"`
	Author   string  `json:"author"`
}

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postID"`
	ParentID  *string    `json:"parentID,omitempty"`
	Content   string     `json:"content"`
	Author    string     `json:"author"`
	CreatedAt string     `json:"createdAt"`
	Replies   []*Comment `json:"replies"`
}

type CreatePostInput struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	Author        string `json:"author"`
	AllowComments *bool  `json:"allowComments,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Author        string     `json:"author"`
	CreatedAt     string     `json:"createdAt"`
	AllowComments bool       `json:"allowComments"`
	Comments      []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
